### ISSUE TITLE
Example collection doesn't work / cannot get script to work 

### ISSUE THREAD

**Issue by tomblenz** [matt-ball/postman-external-require#3]
Your example collection doesn't function: https://app.getpostman.com/run-collection/d76d17db442b465cfe3f

> There was an error in evaluating the test script:  Error: Cannot find module 'slapdash'

I had set the globals to `uniq,slapdash,pad-left`.  The `packages` and `installedPackages` are not set after running.

The console shows an error connecting:
![image](https://user-images.githubusercontent.com/3953262/89831510-161ecb80-dbb2-11ea-911e-15b8832a6980.png)

**Comment by matt-ball** [comment]
Do you have the local node service running described in the readme?

**Comment by tomblenz** [comment]
![image](https://user-images.githubusercontent.com/3953262/89935429-4758d380-dc66-11ea-8de6-69cec473f526.png)
