### ISSUE TITLE
What are global variables packages and installedPackages used for?

### ISSUE THREAD

**Issue by chen83193093** [matt-ball/postman-external-require#6]
_If you want to jump right into it, import this prebuilt collection and create a global variable called require with value uniq,slapdash,pad-left_

For **packages** and **installedPackages** fields, what should they set to be?

**Comment by matt-ball** [comment]
The pre-request script at the collection level (also detailed in the README) programmatically handles these variables. You should leave them untouched. 

The only thing you need to set is the `require` global variable.
